CREATE TABLE [dbo].[Transactions]
(
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Amount] MONEY NOT NULL,
    [Currency] NVARCHAR(20) NOT NULL,
    [From] UNIQUEIDENTIFIER NOT NULL,
    [To] UNIQUEIDENTIFIER NOT NULL,
    [Timestamp] DATETIME NOT NULL
)
